---
- name: Uninstall Java and Apache2
  hosts: all
  become: yes

  tasks:
  - name: Uninstall Apache2 and dependencies
    apt:
      name: apache2
      state: absent
      purge: yes
      autoremove: yes

  - name: Uninstall OpenJDK 17 JRE
    apt:
      name: openjdk-17-jre
      state: absent
      autoremove: yes