---
- hosts: all
  become: yes
  tasks:
    - name: Demo Playbook
      tags: first
      apt: 
        name: apache2 
        state: present

    - name: Demo for starting service
      tags: Second
      service: 
        name: apache2 
        state: started



ansible-playbook playbookname.yml --tags first (Executing the first tag only)
ansible-playbook playbookname.yml --tags second (Executing second tag only) 
ansible-playbook playbookname.yml --list-tags
