---
- name: Install MySQL and nginx
  hosts: all
  become: yes

  tasks:
  - name: Install MySQL
    apt:
      name: mysql-server
      state: present

  - name: Start MySQL service
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: yes